# Generated by Django 2.2.10 on 2020-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_rent', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('price_one', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_two', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bills', models.CharField(blank=True, max_length=255, null=True)),
                ('licensor', models.CharField(blank=True, max_length=255, null=True)),
                ('number_bedrooms', models.IntegerField(default=0)),
                ('deposit_rent', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
