# Generated by Django 2.2.10 on 2020-02-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='address',
            new_name='property',
        ),
    ]
