# Generated by Django 2.2.10 on 2020-02-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20200215_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flats.Flat'),
        ),
    ]
