# Generated by Django 2.2.10 on 2020-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20200215_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='date_to_rent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
