# Generated by Django 2.2.10 on 2020-02-16 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_auto_20200215_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
