# Generated by Django 2.2.10 on 2020-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_flat_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='url',
            new_name='photos',
        ),
    ]
