# Generated by Django 2.2.10 on 2020-02-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_auto_20200219_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='photos',
            new_name='photos_url',
        ),
    ]
